apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wl6qktdyi-go
  janus-idp.io/tekton: wl6qktdyi-go
  backstage.io/kubernetes-id: wl6qktdyi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wl6qktdyi-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
